#Connect Type : Service
#Host : localhost
#Database : FREE
#URL : jdbc:oracle:thin:@//localhost:1521/FREE
#Authentication : User / Password
#User : system
#Password : My1passw
version: '3'
services:
  oracledb:
    image: gvenzl/oracle-free:latest-faststart
    container_name: oracledb
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PASSWORD=My1passw